### ISSUE TITLE
substreams-sink-sql run is crashing with RPC error

### ISSUE THREAD

**Issue by vivekascoder** [streamingfast/substreams-sink-sql#89]
Here are the logs

```
2025-05-01T00:12:17.685+0530 INFO (sink-sql) waiting for run termination
2025-05-01T00:12:17.685+0530 ERRO (sink-sql) stream failure: rpc error: code = Unauthenticated desc = required authorization token not found. Please provide a valid JWT token via 'authorization' header or an API key via 'x-api-key' header
```

this is the substreams.yaml file which is auto generated.
```
# substreams.yaml
specVersion: v0.1.0
package:
  name: my_project_sql
  version: v0.1.0

protobuf:
  excludePaths:
    - sf/substreams/sink
    - sf/substreams/v1
    - sf/substreams/index
    - sf/substreams/intern
    - google

network: solana-devnet
imports:
  sql: https://github.com/streamingfast/substreams-sink-sql/releases/download/protodefs-v1.0.7/substreams-sink-sql-protodefs-v1.0.7.spkg
  database_change: https://github.com/streamingfast/substreams-sink-database-changes/releases/download/v1.2.1/substreams-database-change-v1.2.1.spkg
  my_project: ../my-project-v0.1.0.spkg

binaries:
  default:
    type: wasm/rust-v1
    file: target/wasm32-unknown-unknown/release/my_project_sql.wasm

modules:
  - name: db_out
    kind: map
    initialBlock: 0
    inputs:
      - map: my_project:map_program_data
    output:
      type: proto:sf.substreams.sink.database.v1.DatabaseChanges

sink:
  module: db_out
  type: sf.substreams.sink.sql.v1.Service
  config:
    schema: "./schema.sql"
    engine: postgres
    postgraphile_frontend:
      enabled: true
```

I want to use solana's Devnet network.
